### ISSUE TITLE
existingPasswordSecret is not working

### ISSUE THREAD

**Issue by vrathore18** [bitnami/bitnami-docker-rabbitmq#110]
Rabbitmq is not picking the 
`existingPasswordSecret: secret-variable `

In my sercrt I have defined the 
```
data:    
    rabbitmq-password: test@123
```
but still it is not picking correct secret value.

**Comment by dani8art** [comment]
HI @vrathore18 

Thank you for opening this issue, I would need to know more about your deployment to reproduce it and figure out a solution. Could you share some items with us?

- which version of the chart are you using?
- are you overriding any other value in your deployment?
- how are you building your secret?

As an initial test, could you try to build your secret with a `base64` encoded password?

```
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
```

As we can see here, we are building a `base64` encoded password in our chart definitions, so I guess you should use a `base64` encoded password in your secret as well.

Regards.

**Comment by vrathore18** [comment]
@dani8art 

1. which version of the chart are you using?
name: rabbitmq
version: 6.12.1
appVersion: 3.8.1

what I am trying to achieve is: _I don't want to put rabbitmq password in value.yaml as I am going to put my project in git_.

Now I had this understanding that using below key, I can define password in my secret file and used it.
`# existingPasswordSecret: secret-variable`

below is my secret yaml. I had lots of values there but I am posting only relevant part

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-variable
type: Opaque
stringData:
    DB: "xxxxxx"
data:    
    rabbitmq-password: test@123
```

**Comment by dani8art** [comment]
Hi @vrathore18 di you test using a `base64` value? it works for me. Please try:

**Create secret**
```
$ kubectl create secret generic rabbitmq-password-secret --from-literal=rabbitmq-password=test@123
```
**Or create it manually**
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-variable
type: Opaque
stringData:
    DB: "xxxxxx"
data:    
    rabbitmq-password: dGVzdEAxMjM= # It is `test@123` base64 encode 
```
```
$ helm install rbb \
  --set rabbitmq.existingPasswordSecret=rabbitmq-password-secret \
  stable/rabbitmq
```

**Comment by k8s-learner** [comment]
Can we please reopen this issue? I am facing the same problem. 
@dani8art Your above solution is not fixing the problem. First, I things there was a typo. In your solution when created manually name should be "rabbitmq-password-secret" instead of secret-variable. 

As you suggested I ran

`kubectl create secret generic rabbitmq-password-secret --from-literal=rabbitmq-password=test@123 -n rabbitmq`

Then I set this in value.yaml

```
rabbitmq:
  ## RabbitMQ application username
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  username: user

  ## RabbitMQ application password
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  #password: password
  existingPasswordSecret: rabbitmq-password-secret
```
and I ran the helm
`helm install  stable/rabbitmq   --set rabbitmq.existingPasswordSecret=rabbitmq-password-secret --namespace rabbitmq`

Still it's not taking the correct password.
when I ran this command
`echo "Password      : $(kubectl get secret --namespace rabbitmq trialco-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"`

I am just getting the blank Password
`Password      : `
