### ISSUE TITLE
How to enable persistence for eks AWS 

### ISSUE THREAD

**Issue by vrathore18** [bitnami/bitnami-docker-rabbitmq#111]
I am little confused on how the persistence thing is working on the k8s setup. Below is the snippet which I am using 

```
persistence:
  enabled
  accessMode: ReadWriteOnce
  size: 8Gi
  path: /opt/bitnami/rabbitmq/var/lib/rabbitmq
```

Right now there is no storageclassname defined than how it is working? 

Now my second part is
I want to add storageclassname then will this work?? or do I have to remove path? Also do I need to add existingClaim as well?
```
persistence:
  enabled
  accessMode: ReadWriteOnce
  size: 8Gi
  path: /opt/bitnami/rabbitmq/var/lib/rabbitmq
  storageClass: efs-test1
```

cloud:AWS
storage: efs
I am using bitmani rabbitmq helm chart.
