### ISSUE TITLE
Couldn't inject definitions for custom exchange and queues

### ISSUE THREAD

**Issue by arora-kushal** [bitnami/bitnami-docker-rabbitmq#113]
Hi Team,

I am trying to inject definition file to bitnami image but it is giving following error. 

Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq: could not start kernel pid (application_controller) (invalid config data: invalid application config: {rabbitmq_management,

![image](https://user-images.githubusercontent.com/8510977/77757209-cdc59d80-7056-11ea-87a5-74ded7662c1e.png)

docker-compose.yml

```
services:
  rabbitmq:
    image: bitnami/rabbitmq:3.7.14
    volumes:
      - rabbit_data:/bitnami
      - ./rabbitmq/config:/bitnami/rabbitmq/conf
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_USERNAME=development
      - RABBITMQ_HASHED_PASSWORD=aiBd44L/jX5Sw6KT1BhyovixkyWiM9dDyVR/azWIPubzBOI2 #developer
      - RABBITMQ_VHOST=development
    networks:
      - rabbit-network
```

rabbitmq.config

```[
  {rabbit,
   [
     {tcp_listeners, [5672]},
     {disk_free_limit, {mem_relative, 1.0} },
     {cluster_partition_handling, ignore },
     {default_vhost, <<"development">>},
     {default_user, <<"development">>},
     {default_permissions, [<<".*">>, <<".*">>, <<".*">>]}
   ]
  },
  {rabbitmq_management,
   [
     {listener, [{port, 15672 }, {ip, "0.0.0.0"}]}
   ],
   [
     {load_definitions, "/opt/bitnami/rabbitmq/etc/rabbitmq/definitions.json" }
   ]
  }
].
```

definitions.json

```{
    "exchanges": [
        {
            "name": "MyExchange",
            "vhost": "/",
            "type": "direct",
            "durable": true,
            "auto_delete": false,
            "internal": false,
            "arguments": {}
        }
    ],
    "queues": [
        {
            "name": "MyQueue",
            "vhost": "/",
            "durable": true,
            "auto_delete": false,
            "arguments": {}
        }
    ],  
    "bindings": [
        {
            "source": "MyExchange",
            "vhost": "/",
            "destination": "MyQueue",
            "destination_type": "queue",
            "routing_key": "",
            "arguments": {
                "Noun": "Job",
                "Verb": "Completed"
            }
        }
    ]
}```
