### ISSUE TITLE
Unable to use persistence parameters

### ISSUE THREAD

**Issue by ggeighty8** [bitnami/bitnami-docker-rabbitmq#156]
**Unable to use persistence parameters**

I am trying to disable RabbitMQ data persistence using PVC. I tried setting `persistence.enabled=false` but I get this exception:
```
StatefulSet.apps "rabbitmq-cluster-bitnami" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
If I remove the mentioned parameter, the RMQ deploys successfully. 
I referred to this document: https://artifacthub.io/packages/helm/bitnami/rabbitmq#persistence-parameters

Following is the `Values.yaml` I am using to deploy RMQ on my kuberneties cluster. 

```
rabbitmq:
  replicaCount: 3
  nodeSelector: 
    service: rmq
    component: rmq
    app: events
  persistence:
    enabled: false
  extraConfiguration: |-
    disk_free_limit.absolute = 5GB
    delegate_count = 64
    heartbeat = 60
    queue_index_embed_msgs_below = 0
    management.load_definitions = /app/load_definition.json
  loadDefinition:
    enabled: true
    existingSecret: rabbitmq-load-definition
```

What I want to do is disable persistence for my RMQ deployment.
