### ISSUE TITLE
springboot connect rabbitmq 5672 error

### ISSUE THREAD

**Issue by zhangwei900808** [bitnami/bitnami-docker-rabbitmq#170]
I was used helm to install rabbitmq ，the below is my values.yaml
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  hostName: rabbitmq.testapi.seaurl.com
#  path: /rabbitmq
  tls: true
  tlsSecret: rabbitmq-tls
persistence:
  storageClass: "alicloud-disk-ssd"
  size: 20Gi
```

and it is work 
![image](https://user-images.githubusercontent.com/4385154/124590026-3ff97480-de8d-11eb-8e14-ff3ccddb571d.png)

and I used k8s dns rabbitmq address it is work

application.yml
```
spring:
  rabbitmq:
    host: test-rabbitmq-headless.rabbit.svc.cluster.local
    port: 5672
    username:
    password:
```

but when I used hostname and run  ```mvn spring-boot:run``` is not work 
application.yml
```
spring:
  rabbitmq:
    host: rabbitmq.testapi.seaurl.com
   # 5672 is not work yet
    port: 80
    username:
    password:
```
version:
helm: v3.6.0
chart：6.18.2，
APP：3.8.2
