### ISSUE TITLE
Mac M1 - Unable to run

### ISSUE THREAD

**Issue by nskaiser** [bitnami/bitnami-docker-rabbitmq#174]
Hello, I have been unable to get this docker image running on an M1:

Attaching to rabbitmq_rabbitmq_1
rabbitmq_1  | rabbitmq 15:17:11.29
rabbitmq_1  | rabbitmq 15:17:11.31 Welcome to the Bitnami rabbitmq container
rabbitmq_1  | rabbitmq 15:17:11.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq_1  | rabbitmq 15:17:11.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq_1  | rabbitmq 15:17:11.37
rabbitmq_1  | rabbitmq 15:17:11.39 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq_1  | rabbitmq 15:17:11.50 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq_1  | rabbitmq 15:17:11.67 INFO  ==> Initializing RabbitMQ...
rabbitmq_1  | rabbitmq 15:17:11.82 INFO  ==> Starting RabbitMQ in background...
rabbitmq_1  | /opt/bitnami/scripts/libos.sh: line 252:   101 Aborted                 "$@" > /dev/null 2>&1
rabbitmq_1  | /opt/bitnami/scripts/libos.sh: line 252:   170 Aborted                 "$@" > /dev/null 2>&1
rabbitmq_1  | rabbitmq 15:18:55.39 ERROR ==> Couldn't start RabbitMQ in background.
rabbitmq_rabbitmq_1 exited with code 1

My docker-compose is:

```
version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.9
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - 'rabbitmq_data:/bitnami'
volumes:
  rabbitmq_data:
    driver: local
```
