### ISSUE TITLE
Couldn't start RabbitMQ in background without further error message

### ISSUE THREAD

**Issue by meesha7** [bitnami/bitnami-docker-rabbitmq#175]
**Description**

Trying to deploy RabbitMQ to Openshift/k8s, it starts but after a while fails.

The only log output I get is this:

```
rabbitmq 10:50:21.59 
rabbitmq 10:50:21.60 Welcome to the Bitnami rabbitmq container
rabbitmq 10:50:21.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq 10:50:21.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq 10:50:21.60 
rabbitmq 10:50:21.60 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 10:50:21.61 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 10:50:21.63 INFO  ==> Initializing RabbitMQ...
rabbitmq 10:50:21.73 INFO  ==> Starting RabbitMQ in background...
rabbitmq 10:53:36.80 ERROR ==> Couldn't start RabbitMQ in background.
rabbitmq 10:53:36.80 INFO  ==> Stopping RabbitMQ...
```

**Image**

I'm using the `quay.io/bitnami/rabbitmq:3.8-debian-10` image.

**DeploymentConfig**

```yaml
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: rabbitmq
  namespace: redacted
  labels:
    app: rabbitmq
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        containerNames:
          - rabbitmq
        from:
          kind: ImageStreamTag
          namespace: redacted
          name: 'rabbitmq:latest'
        lastTriggeredImage: >-
          redacted
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: rabbitmq
    service: rabbitmq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq
        service: rabbitmq
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: rabbitmq-secret
            defaultMode: 420
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-volume
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          name: rabbitmq
          livenessProbe:
            tcpSocket:
              port: 5671
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: erlang_cookie
            - name: RABBITMQ_DEFAULT_USER
              value: redacted
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: default_pass
            - name: RABBITMQ_SSL_CERTFILE
              value: /etc/rabbitmq-secret/cert
            - name: RABBITMQ_SSL_KEYFILE
              value: /etc/rabbitmq-secret/key
            - name: RABBITMQ_SSL_CACERTFILE
              value: /etc/rabbitmq-secret/ca
            - name: RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT
              value: 'false'
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: '-rabbitmq_management listener [{ssl,false}]'
            - name: RABBITMQ_LOGS
              value: '-'
            - name: RABBITMQ_LOG
              value: 'debug,-color'
          ports:
            - containerPort: 5671
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
            - containerPort: 4369
              protocol: TCP
            - containerPort: 15692
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: /etc/rabbitmq-secret
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
          terminationMessagePolicy: File
          image: >-
            redacted
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      hostname: rabbitmq
      schedulerName: default-scheduler
```

I added these env values:

```yaml
  - name: RABBITMQ_LOGS
    value: '-'
  - name: RABBITMQ_LOG
    value: 'debug,-color'
```

in hope to get more output. There are no logs on the rabbitmq volume (/var/log or /var/lib/rabbitmq/...).

What other information is needed to debug this? How can I enable more logging?
