### ISSUE TITLE
Management Console asking for basic auth after entering login credentials

### ISSUE THREAD

**Issue by kailashyogeshwar85** [bitnami/bitnami-docker-rabbitmq#183]
**Description**

**Steps to reproduce the issue:**

1. Create compose file with image bitnami/latest with env 

> RABBITMQ_USERNAME 

> RABBITMQ_PASSWORD

> RABBITMQ_PLUGINS: rabbitmq_management,rabbitmq_delayed_message_exchange,rabbitmq_consistent_hash_exchange

2. Access management UI at http://127.0.0.1:15672
3. Opens login page enter the credentials.Basic auth credentials window pops up.

**Describe the results you received:**

User is not able to login due to basic auth credentials failure.
Also additional basicauth screen is shown after entering login credentials.

**Describe the results you expected:**
basic auth should not be shown once login credentials are entered.

Login to management console.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
bitnami:latest

- Output of `docker version`:
Docker version 20.10.10, build b485636

```
rabbitmq    | 2021-11-16 11:21:52.586423+00:00 [warn] <0.1140.0> HTTP access denied: user 'admin' - invalid credentials
rabbitmq    | 2021-11-16 11:21:56.765608+00:00 [warn] <0.1143.0> HTTP access denied: user 'admin' - invalid credentials
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)
```
- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

```
 rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
      RABBITMQ_PLUGINS: rabbitmq_management,rabbitmq_delayed_message_exchange,rabbitmq_consistent_hash_exchange
    ports:
      - 5671:5671
      - 15672:15672
    volumes:
     - ./volumes/queuedata:/bitnami
```

![Screenshot from 2021-11-16 16-33-38](https://user-images.githubusercontent.com/11419095/141977505-3d60a3b2-b762-4047-81e0-c21c457893d4.png)

**Comment by miguelaeh** [comment]
Hi @kailashyogeshwar85 ,
Checking the logs you shared it seems the password you are introducing is wrong. Could you try deleting the volumes in case it was configured to a different password first and re-try?

**Comment by owencjones** [comment]
> Hi @kailashyogeshwar85 , Checking the logs you shared it seems the password you are introducing is wrong. Could you try deleting the volumes in case it was configured to a different password first and re-try?

I've had the same issue, and nothing appears in the logs, except the usual messages for invalid credentials, but clearing the volume does work.

Not ideal though, because obviously you lose whatever you were storing.

**Comment by miguelaeh** [comment]
Tha happens because you probably had an old volume from a previous installation or you upgraded the chart without providing the old password.

**Comment by owencjones** [comment]
> Tha happens because you probably had an old volume from a previous installation or you upgraded the chart without providing the old password.

No, it happens even without making changes, just by leaving it running for a while.  For me, the following steps cause it consistently:

1. Delete all applicable volumes etc
2. `docker-compose.yml` setup only currently runs the rabbitmq (other services to be added)
3. volume setup in `docker-compose.yml` as-per the volume example on Dockerhub
4. `docker-compose up`
5. Login
6. Wait for session to time out
7. Try to login again
8. Login page calls `/whoami` and receives `401` answer, forwards to a Basic Auth dialog which doesn't seem to work with any creds setup, either in Env vars, nor in management console.
9. Logs just have the usual entry for a wrong password - despite it being the same as previously accepted

**Comment by miguelaeh** [comment]
I tried to follow those steps but I was unable to reproduce the issue. I used this docker-compose: 
```
version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.9
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
volumes:
  rabbitmq_data:
    driver: local
```
