### ISSUE TITLE
probes fail when installing into kubernetes without using helm

### ISSUE THREAD

**Issue by jar349** [bitnami/bitnami-docker-rabbitmq#62]
**Description**
I am trying to install rabbitMQ into my minikube (0.24.1) running kubernetes 1.8.0.  The helm chart uses a PersistentVolumeClaim, which will not work for me.  Here's what I've got:

A folder on my macbook: `~/.data`

this folder is shared with my minkube VM like so:
`VBoxManage sharedfolder add "minikube" --name "data-dir" --hostpath "$HOME/.data"`
and then I mount that shared folder in the minikube VM:
`sudo mount -t vboxsf data-dir /data`

And so now, I can use hostPath volumes in my kubernetes pods, setting their path to something like:
```yaml
volumes:
      - name: data-dir
        hostPath:
          path: /data/rabbitmq <-- path on minikube VM, also `~/.data/rabbitmq` on my mac
          type: DirectoryOrCreate
```
and then I can define the following volumeMount:
```yaml
volumeMounts:
        - name: data-dir
          mountPath: /bitnami/rabbitmq  <-- where the docker container writes stuff
``` 

To make this work, I stole the yaml from the helm chart templates and just hard-coded the values instead of running values.yaml through the go template engine, leaving me with this YAML:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  labels:
    app: rabbitmq
type: Opaque
data:
  rabbitmq-password: dmVyeWxvY2Fsc2VjcmV0
  rabbitmq-erlang-cookie: MjFRVWV4T1oxVURHYzVnTGhzUU9RU2JYMFBZMlFRcTk=
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: dist
    port: 25672
    targetPort: dist
  - name: stats
    port: 15672
    targetPort: stats
  selector:
    app: rabbitmq
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: bitnami/rabbitmq:3.7.2-r1
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_USERNAME
          value: "admin"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: rabbitmq-password
        - name: RABBITMQ_ERL_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: rabbitmq-erlang-cookie
        - name: RABBITMQ_NODE_PORT_NUMBER
          value: "5672"
        - name: RABBITMQ_NODE_TYPE
          value: "stats"
        - name: RABBITMQ_NODE_NAME
          value: "rabbit@localhost"
        - name: RABBITMQ_CLUSTER_NODE_NAME
          value: ""
        - name: RABBITMQ_VHOST
          value: "/"
        - name: RABBITMQ_MANAGER_PORT_NUMBER
          value: "15672"
        - name: RABBITMQ_DISK_FREE_LIMIT
          value: "\"2GiB\""
        ports:
        - name: epmd
          containerPort: 4369
        - name: amqp
          containerPort: 5672
        - name: dist
          containerPort: 25672
        - name: stats
          containerPort: 15672
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
        - name: data-dir
          mountPath: /bitnami/rabbitmq
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
      securityContext:
        fsGroup: 0
        runAsUser: 0
      volumes:
      - name: data-dir
        hostPath:
          path: /data/rabbitmq
          type: DirectoryOrCreate
```

In the dashboard, this is what I see:
```
Readiness probe failed: Status of node rabbit@localhost ... 
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell) 
Error: unable to perform an operation on node 'rabbit@localhost'. Please see diagnostics information and suggestions below. Most common reasons for this are: 
* Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues) 
* CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server) 
* Target node is not running In addition to the diagnostics info below: 
* See the CLI, clustering and networking guides on http://rabbitmq.com/documentation.html to learn more 
* Consult server logs on node rabbit@localhost 
DIAGNOSTICS =========== attempted to contact: [rabbit@localhost] rabbit@localhost: 
* connected to epmd (port 4369) on localhost 
* epmd reports: node 'rabbit' not running at all other nodes on localhost: [rabbitmqcli56] 
* suggestion: start the node Current node details: 
* node name: 'rabbitmqcli56@rabbitmq-8fb85b5c5-nk85t' 
* effective user's home directory: /opt/bitnami/rabbitmq/.rabbitmq 
* Erlang cookie hash: YgzPzLYV2l0ZxISpbGoIMw==
```

If you look in there, you'll see two concerning things:
1. current node details says there's a `rabbitmqcli56@rabbitmq-8fb85b5c5-nk85t` running, but not `rabbit@localhost`.   Obviously, `rabbitmq-8fb85b5c5-nk85t` is the name of the pod that gets created
1. Erlang cookie hash is: `YgzPzLYV2l0ZxISpbGoIMw==` which I assume is just the cookie base64 encoded?  If so, then my base64 encoded cookie is (from my secrets file): `MjFRVWV4T1oxVURHYzVnTGhzUU9RU2JYMFBZMlFRcTk=`.  But it says hash so maybe it hashes my cookie and then base64 encodes that?  I'm not sure if this is a problem or not.

Remember how I said I just stole the yaml from the helm chart?  It's true... which is why this is a weird error: if I install rabbitmq via helm, everything Just Works:

`helm install --name rabbitmq --set rabbitmqUsername=rabbit,rabbitmqPassword=suchpasswordwowamaze,rabbitmqErlangCookie=1234567890abcdefg stable/rabbitmq`

Of course, this uses a PVC instead of a hostPath volume, but the yaml that got sent has got to be exceedinly similar.  I'm going to copy and paste it here from the dashboard:
```json
{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "rabbitmq-rabbitmq",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/rabbitmq-rabbitmq",
    "uid": "8b37d268-10dc-11e8-b922-080027cd4b60",
    "resourceVersion": "58490",
    "generation": 1,
    "creationTimestamp": "2018-02-13T16:40:04Z",
    "labels": {
      "app": "rabbitmq-rabbitmq",
      "chart": "rabbitmq-0.5.3",
      "heritage": "Tiller",
      "release": "rabbitmq"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "rabbitmq-rabbitmq"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "rabbitmq-rabbitmq"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "data",
            "persistentVolumeClaim": {
              "claimName": "rabbitmq-rabbitmq"
            }
          }
        ],
        "containers": [
          {
            "name": "rabbitmq-rabbitmq",
            "image": "bitnami/rabbitmq:3.6.10-r0",
            "ports": [
              {
                "name": "epmd",
                "containerPort": 4369,
                "protocol": "TCP"
              },
              {
                "name": "ampq",
                "containerPort": 5672,
                "protocol": "TCP"
              },
              {
                "name": "dist",
                "containerPort": 25672,
                "protocol": "TCP"
              },
              {
                "name": "stats",
                "containerPort": 15672,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "RABBITMQ_USERNAME",
                "value": "rabbit"
              },
              {
                "name": "RABBITMQ_PASSWORD",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "rabbitmq-rabbitmq",
                    "key": "rabbitmq-password"
                  }
                }
              },
              {
                "name": "RABBITMQ_ERLANG_COOKIE",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "rabbitmq-rabbitmq",
                    "key": "rabbitmq-erlang-cookie"
                  }
                }
              },
              {
                "name": "RABBITMQ_NODE_PORT",
                "value": "5672"
              },
              {
                "name": "RABBITMQ_NODE_TYPE",
                "value": "stats"
              },
              {
                "name": "RABBITMQ_NODE_NAME",
                "value": "rabbit@localhost"
              },
              {
                "name": "RABBITMQ_CLUSTER_NODE_NAME"
              },
              {
                "name": "RABBITMQ_VHOST",
                "value": "/"
              },
              {
                "name": "RABBITMQ_MANAGER_PORT",
                "value": "15672"
              }
            ],
            "resources": {
              "requests": {
                "cpu": "100m",
                "memory": "256Mi"
              }
            },
            "volumeMounts": [
              {
                "name": "data",
                "mountPath": "/bitnami/rabbitmq"
              }
            ],
            "livenessProbe": {
              "exec": {
                "command": [
                  "rabbitmqctl",
                  "status"
                ]
              },
              "initialDelaySeconds": 120,
              "timeoutSeconds": 5,
              "periodSeconds": 10,
              "successThreshold": 1,
              "failureThreshold": 6
            },
            "readinessProbe": {
              "exec": {
                "command": [
                  "rabbitmqctl",
                  "status"
                ]
              },
              "initialDelaySeconds": 10,
              "timeoutSeconds": 3,
              "periodSeconds": 5,
              "successThreshold": 1,
              "failureThreshold": 3
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    }
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2018-02-13T16:40:04Z",
        "lastTransitionTime": "2018-02-13T16:40:04Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}
```

And all is well:
![screen shot 2018-02-13 at 11 46 31 am](https://user-images.githubusercontent.com/290154/36162127-8fce72fe-10b3-11e8-8a9f-db8456bd42df.png)

So why on earth do the probes work in this instance but not when I'm using my YAML above?

**Version**

- Output of `docker version`:

```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.23
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.06.0-ce
  API version:	1.30 (minimum version 1.12)
  Go version:	go1.8.3
  Git commit:	02c1d87
  Built:	Fri Jun 23 21:51:55 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
$ docker info
Containers: 24
 Running: 14
 Paused: 0
 Stopped: 10
Images: 22
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: N/A (expected: )
Security Options:
 seccomp
Kernel Version: 4.9.13
Operating System: Buildroot 2017.02
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 9.765GiB
Name: minikube
ID: UIAS:MFVG:BWRW:B54W:M5YE:2YDU:ZKI6:JIUJ:YWF3:WQMY:3U3S:M5KR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 10.96.0.0/12
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
N/A
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
minikube 0.24.1
kubernetes 1.8.0
