### ISSUE TITLE
[Kubernetes] Cannot login to the Management UI

### ISSUE THREAD

**Issue by tgropper** [bitnami/bitnami-docker-rabbitmq#65]
**Description**

Cannot login to the Managment UI (`http://<IP>:15672`). I've tried using `helm` on kubernetes, `kubectl apply` with the parsed yaml and pure `docker run`.

**Steps to reproduce the issue:**

1. `docker run --name rabbitmq bitnami/rabbitmq:3.7.4-r1`
2. browse to `http://<IP>:15672`
3. user: user / pass: bitnami

**Describe the results you received:**

Login failed.

**Describe the results you expected:**

Login successfuly to Management UI.

**Additional information you deem important (e.g. issue happens only occasionally):**

Not working on kubernetes nor standalone docker.
In kubernetes I've also tried adding env vars `RABBITMQ_DEFAULT_USER` and `RABBITMQ_DEFAULT_PASS`, with and without using kubernetes secrets.

**Version**

charts
* 0.6.26
* 0.6.23

docker images
* 3.7.4-r1
* 3.7.3-r8

```
$ sudo docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:10:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:46 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
```
$ sudo cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```

**Comment by juan131** [comment]
Hi @tgropper I was unable to reproduce the issue using the `docker-compose.yml`. I just simply run:

```
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-rabbitmq/master/docker-compose.yml > docker-compose.yml
docker-compose up
```

And then I browse to http://127.0.0.1:15672

Using **user** and **bitnami** I could login into it

Could you try it?

**Comment by tgropper** [comment]
@juan131 it worked. I had that port in use with another container that was overlapping the exposed port, so I was trying to login to different rabbit instance. Apologies for that!

**BUT** I still can't login using kubernetes. More info:

**helm generated yaml** (removed pass from the secret)
```yaml
# Source: rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-s
  labels:
    app: rabbitmq-s
    chart: "rabbitmq-0.6.25"
    release: "rabbitmq-s"
type: Opaque
data:
  rabbitmq-erlang-cookie: "Q1ZneDBEZmxtbFdETmtveU1uU0dOQ29kUXBnbDFjUWI="
---
# Source: rabbitmq/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-s
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
# Source: rabbitmq/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-s
  labels:
    app: rabbitmq-s
    chart: "rabbitmq-0.6.25"
    release: "rabbitmq-s"
spec:
  type: ClusterIP
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: dist
    port: 25672
    targetPort: dist
  - name: stats
    port: 15672
    targetPort: stats
  selector:
    app: rabbitmq-s
---
# Source: rabbitmq/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-s
  labels:
    app: rabbitmq-s
    chart: "rabbitmq-0.6.25"
    release: "rabbitmq-s"
spec:
  template:
    metadata:
      labels:
        app: rabbitmq-s
    spec:
      containers:
      - name: rabbitmq-s
        image: "bitnami/rabbitmq:3.7.4-r1"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: RABBITMQ_USERNAME
          value: "rabbitmq"
        - name: RABBITMQ_DEFAULT_USER
          value: "rabbitmq"
        - name: RABBITMQ_PASSWORD
          value: "rabbitmq"
        - name: RABBITMQ_DEFAULT_PASS
          value: "rabbitmq"
        - name: RABBITMQ_ERL_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq-s
              key: rabbitmq-erlang-cookie
        - name: RABBITMQ_NODE_PORT_NUMBER
          value: "5672"
        - name: RABBITMQ_NODE_TYPE
          value: "stats"
        - name: RABBITMQ_NODE_NAME
          value: "rabbit@localhost"
        - name: RABBITMQ_CLUSTER_NODE_NAME
          value: ""
        - name: RABBITMQ_VHOST
          value: "/"
        - name: RABBITMQ_MANAGER_PORT_NUMBER
          value: "15672"
        - name: RABBITMQ_DISK_FREE_LIMIT
          value: "\"6GiB\""
        ports:
        - name: epmd
          containerPort: 4369
        - name: amqp
          containerPort: 5672
        - name: dist
          containerPort: 25672
        - name: stats
          containerPort: 15672
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /bitnami/rabbitmq
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rabbitmq-s
```

**POD logs**
```
Welcome to the Bitnami rabbitmq container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
Send us your feedback at containers@bitnami.com
 nami    INFO  Initializing rabbitmq
rabbitm INFO  Creating RabbitMQ System User...
rabbitm INFO  Setting RabbitMQ environment...
rabbitm INFO  Starting RabbitMQ node rabbit@localhost...
rabbitm INFO  Configuring RabbitMQ permissions...
rabbitm INFO 
rabbitm INFO  ########################################################################
rabbitm INFO   Installation parameters for rabbitmq:
rabbitm INFO     Persisted data and properties have been restored.
rabbitm INFO     Any input specified will not take effect.
rabbitm INFO   This installation requires no credentials.
rabbitm INFO  ########################################################################
rabbitm INFO 
nami    INFO  rabbitmq successfully initialized
INFO  ==&gt; Starting rabbitmq... 
 Copyright (C) 2007-2018 Pivotal Software, Inc.
 Licensed under the MPL.  See http://www.rabbitmq.com/
2018-03-22 12:01:31.894 [info] &lt;0.245.0&gt; 
 node           : rabbit@localhost
 home dir       : /opt/bitnami/rabbitmq/.rabbitmq
 config file(s) : /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.config
 cookie hash    : mjXid+6J2ggYTij3OBDP/Q==
 log(s)         : /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@localhost.log
                : /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@localhost_upgrade.log
 database dir   : /opt/bitnami/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@localhost
```
