### ISSUE TITLE
[BUG] Can not define username and password via env on 3.7-debian-9

### ISSUE THREAD

**Issue by dennybaa** [bitnami/bitnami-docker-rabbitmq#77]
To reproduce use this `docker-compose.yml`:

```yaml
version: '2'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7-debian-9'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    environment:
      - RABBITMQ_PASSWORD=strong
      - RABBITMQ_USERNAME=my
volumes:
  rabbitmq_data:
    driver: local
```

Start `docker-compose up --force-recreate` and try to login to `http://localhost:15672` with username: `my` and password: `strong`.

Instead it just picks up the defaults `user:bitnami`.

Guys, any ides how to fix this?
