### ISSUE TITLE
 Error executing 'postInstallation': Cannot change password for user

### ISSUE THREAD

**Issue by pravien96** [bitnami/bitnami-docker-rabbitmq#79]
Hello
when i run a docker or docker-compose up 
its giving a error on start up like 
" Error executing 'postInstallation': Cannot change password for user john"

this is my docker compose file
johnqueue:
                image: 'bitnami/rabbitmq:latest'
                environment:
                        RABBITMQ_USERNAME: "john"
                        RABBITMQ_PASSWORD: "john@123"
                        RABBITMQ_VHOST: "/"
                        RABBITMQ_ERL_COOKIE: "abcdefg"

**Comment by andresbono** [comment]
Hi @pravien96, thanks for submitting this issue.

We have checked your configuration for RabbitMQ with the following _docker-compose_ and we can't experience your issue.

```
version: '2'

services:
  johnqueue:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - 15672:15672
    environment:
      - 'RABBITMQ_USERNAME=john'
      - 'RABBITMQ_PASSWORD=john@123'
      - 'RABBITMQ_VHOST=/'
      - 'RABBITMQ_ERL_COOKIE=abcdefg'
```

The password is changed and you can access RabbitMQ admin panel without any problem.

Can you check if it is an error in the syntax when defining the environment variables?

-Andrés B.
